### ISSUE TITLE
Setting direct_lvm.enabled to false, still ran the docker-storage playbook

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#1031]
**BUG REPORT**:

**What happened**:

Setting the `storage.direct_lvm.enabled` to `false` (see below) still created the thinpool

```
storage:
    direct_lvm:
      enabled: false
```

**What you expected to happen**:

It should **not** be running the `docker-storage` playbook

**How to reproduce it (as minimally and precisely as possible)**:

Set the `storage.direct_lvm.enabled` to `false` (see below) still created the thinpool

```
storage:
    direct_lvm:
      enabled: false
```

**Anything else we need to know?**:

I think this is because https://github.com/apprenda/kismatic/blob/master/ansible/roles/docker-storage/tasks/main.yaml#L4 should be `direct_lvm` and not `directlvm`.

**Environment**:
- Kismatic version: 1.7.0

**Comment by dkoshkin** [comment]
I was not able to reproduce it:
```
Install Docker
- Running task: install docker-ce yum package
  worker001                                                                     [OK]
  etcd001                                                                       [OK]
  master001                                                                     [OK]
- Running task: install docker-ce deb package
  worker001                                                                     [SKIPPED]
  master001                                                                     [SKIPPED]
  etcd001                                                                       [SKIPPED]
- Running task: install lvm2 package
  worker001                                                                     [SKIPPED]
  master001                                                                     [SKIPPED]
  etcd001                                                                       [SKIPPED]
...
```
Here is the `clustercatalog.yaml` contents for that run, as you can see it is `directlvm` (although it should be changed to be consistent with the plan file)
```
docker:
  logs:
    driver: json-file
    opts:
      max-file: "1"
      max-size: 50m
  storage:
    directlvm:
      enabled: false
      block_device: ""
      enable_deferred_deletion: false
```

Plan file for reference:
```
docker:
  logs:
    driver: json-file
    opts:
      max-file: "1"
      max-size: 50m

  storage:

    # Configure devicemapper in direct-lvm mode (RHEL/CentOS only).
    direct_lvm:
      enabled: false
```
