### ISSUE TITLE
The kube-proxy DaemonSet should include an upgrade strategy

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#1034]
The kube-proxy DaemonSet should really have:

```
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
``` 

As part of its manifest to allow for graceful upgrades.
