### ISSUE TITLE
Provide the ability to add taints to nodes

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#1057]
It would be useful to allow for taints to be added to all nodes (excluding etcd).

**Suggested layout:**

```
taints:
      NoSchedule:
        key: value
        key: value
      NoExecute:  {}
      PreferNoSchedule: {}
```

@dkoshkin @willvrny thoughts?
