### ISSUE TITLE
Disable insecure-bind-address and insecure-port on kube-apiserver

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#1134]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
Flags `--insecure-bind-address` and `--insecure-port` are set to `127.0.0.1:8080`, although it can only be accessed from the node itself it is still recommended to disable insecure access to the k8s API.

**What you expected to happen**:
The k8s API to be only accessible via the authenticated port, `6443`

**How to reproduce it (as minimally and precisely as possible)**:
Use current version of KET.

**Anything else we need to know?**:
When disabling insecure access loose the ability to use that port for liveliness/readiness probes, the pod gets restarted because the secure endpoint returns a `403`. Need to figure out how to properly setup probes. 

https://github.com/kubernetes/kubernetes/issues/43784

**Comment by leehanel** [comment]
@dkoshkin  is there a follow on issue to fix the probes?

**Comment by dkoshkin** [comment]
@leehanel the PR addressed that, basically the probes will use the authenticated ports and automatically get the `system:unauthenticated` RBAC group:
```
  rules:
  - nonResourceURLs:
    - /api
    - /api/*
    - /apis
    - /apis/*
    - /healthz
    - /swagger-2.0.0.pb-v1
    - /swagger.json
    - /swaggerapi
    - /swaggerapi/*
    - /version
    verbs:
    - get
```

This is the recommended approach by the community.
