### ISSUE TITLE
Support Weave Encryption

### ISSUE THREAD

**Issue by davidhiendl** [apprenda/kismatic#1155]
**FEATURE REQUEST**:

Currently Weave encryption is not officially supported. It can easily be enabled by setting a env variable for the weave containers or supply the password to it's configuration file.

This would allow running Kismatic in potentially hostile environments where a private network is not available and traffic may be read by other clients (ex.: various cloud providers).

Excerpt from `ansible/playbooks/roles/weave/templates/weave.yaml` line 115+:
```yaml
           env:
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: IPALLOC_RANGE
                  value: "{{ kubernetes_pods_cidr }}"
                - name: WEAVE_PASSWORD
                  value: "{{ variable passed in from configuration ins kismatic-cluster.yaml }}"
```

**Environment**:
- Kismatic version: 1.9.0
