### ISSUE TITLE
smoke test  ERROR

### ISSUE THREAD

**Issue by henghasaint** [apprenda/kismatic#1159]
##############################################
```
Running Smoke Test==================================================================
Smoke Test Master Node
- Running task: Gathering Facts
  k8smaster01c7                                                                 [OK]
- Running task: copy Kuberang to node
  k8smaster01c7                                                                 [OK]
- Running task: run smoke test checks using Kuberang
  k8smaster01c7                                                                 [ERROR]
---- STDOUT ----
Kubectl configured on this node                                                 [OK]
Delete existing deployments if they exist                                       [OK]
Nginx service does not already exist                                            [OK]
BusyBox service does not already exist                                          [OK]
Nginx service does not already exist                                            [OK]
Issued BusyBox start request                                                    [OK]
Issued Nginx start request                                                      [OK]
Issued expose Nginx service request                                             [OK]
Both deployments completed successfully within timeout                          [ERROR]
Powered down Nginx service                                                      [OK]
Powered down Busybox deployment                                                 [OK]
Powered down Nginx deployment                                                   [OK]
---- STDERR ----
Error running command: Failed to deploy test workloads
---------------
Smoke Test Master Node Finished
error running smoke test: error running playbook: error running ansible: exit status 2
```
##################################

**Environment**:
- Kismatic version :1.8.1
- Plan file Gist:
+++++++++++++++++++
```
cluster:
  name: kubernetes

  version: v1.9.2

  disable_package_installation: true

  disconnected_installation: true

  networking:

    pod_cidr_block: 172.164.0.0/16

    service_cidr_block: 172.204.0.0/16

    update_hosts_files: true
    http_proxy: ""
    https_proxy: ""

    no_proxy: ""

  certificates:
    expiry: 175200h
    ca_expiry: 175200h

  ssh:

    user: kismaticuser

    ssh_key: /root/kismaticuser.key
    ssh_port: 22

  kube_apiserver:
    option_overrides: {}

  kube_controller_manager:
    option_overrides: {}

  kube_scheduler:
    option_overrides: {}

  kube_proxy:
    option_overrides: {}

  kubelet:
    option_overrides: {}

  cloud_provider:

    provider: ""

    config: ""

docker:

  disable: true
  logs:
    driver: json-file
    opts:
      max-file: "1"
      max-size: 50m

  storage:

    driver: ""
    opts: {}

    direct_lvm_block_device:

      path: ""
      thinpool_percent: "95"
      thinpool_metapercent: "1"
      thinpool_autoextend_threshold: "80"
      thinpool_autoextend_percent: "20"

docker_registry:
  server: "registry.wutong.com"
  CA: "/root/ca.crt"

  username: "admin"

  password: "Harbor12345"

add_ons:
  cni:
    disable: false

    provider: calico
    options:
      calico:

        mode: overlay

        log_level: info

        workload_mtu: 1500

        felix_input_mtu: 1440

  dns:
    disable: true

    # Options: 'kubedns','coredns'.
    provider: kubedns

  heapster:
    disable: false
    options:
      heapster:
        replicas: 2

        service_type: ClusterIP

        sink: influxdb:http://heapster-influxdb.kube-system.svc:8086

      influxdb:
        pvc_name: ""

  dashboard:
    disable: false

  package_manager:
    disable: true

    provider: helm
    options:
      helm:
        namespace: kube-system

  rescheduler:
    disable: true

etcd:
  expected_count: 3

  internal
  nodes:
  - host: "k8setc01c7"
    ip: "192.168.0.183"
    internalip: ""

  - host: "k8setc02c7"
    ip: "192.168.0.184"
    internalip: ""

  - host: "k8setc03c7"
    ip: "192.168.0.185"
    internalip: ""

master:
  expected_count: 2

  load_balanced_fqdn: "192.168.0.187"
  load_balanced_short_name: "k8smaster01c7"
  nodes:
  - host: "k8smaster01c7"
    ip: "192.168.0.187"
    internalip: ""
    labels: {}

  - host: "k8smaster02c7"
    ip: "192.168.0.188"
    internalip: ""
    labels: {}

worker:
  expected_count: 3
  nodes:
  - host: "k8snode01c7"
    ip: "192.168.0.221"
    internalip: ""
    labels: {}

  - host: "k8snode02c7"
    ip: "192.168.0.222"
    internalip: ""
    labels: {}

  - host: "k8snode03c7"
    ip: "192.168.0.223"
    internalip: ""
    labels: {}

ingress:
  expected_count: 1
  nodes:
  - host: "k8singress01c7"
    ip: "192.168.0.189"
    internalip: ""
    labels: {}

storage:
  expected_count: 0
  nodes: []

nfs:
  nfs_volume: []
```
+++++++++++++++++++ 
- Cloud provider or hardware configuration:KVM 
- OS (e.g. from /etc/os-release): vm CentOS7.4
- Kernel:3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27
