### ISSUE TITLE
Kismatic Inspector Issues for Master and Worker nodes

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#1162]
**What happened**: The Kismatic Inspector on KET 1.9.0 has the following errors: 

1. The worker nodes need to allow ports 2379, 2380, 6660 and 6666 outbound to pass

2. The master nodes need to allow ports 2380 and 6660 outbound to pass 

**What you expected to happen**:

- The worker nodes do not require access to etcd **at all** so all ports should not be required.
- The master nodes should **not** require outbound rules to the k8s and calico etcd **peer** ports.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kismatic version: 1.9.0

**Comment by dkoshkin** [comment]
@swade1987 it would be good to get a full output of the failures, looking at the rules:
```
# Ports used by etcd are accessible
- kind: TCPPortAccessible
  when: 
  - ["etcd"]
  port: 2379
  timeout: 5s
- kind: TCPPortAccessible
  when: 
  - ["etcd"]
  port: 6666
  timeout: 5s
- kind: TCPPortAccessible
  when: 
  - ["etcd"]
  port: 2380
  timeout: 5s
- kind: TCPPortAccessible
  when: 
  - ["etcd"]
  port: 6660
  timeout: 5s
```
These should only apply to nodes that have the `etcd` role, if they are being run on other nodes than the bug is not in the rules but how we check what rules should be executed.
