### ISSUE TITLE
docker http_proxy settings missing

### ISSUE THREAD

**Issue by pablodav** [apprenda/kismatic#1196]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**: behind proxy, http_proxy settings for docker.service unit needs to be set.

Just noticed when working behind proxy, download tasks with docker pull doesn't works because there is no http_proxy environment for docker.service.

This needs to be setup:

```
cat /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://user:pass@hostname:8080"
Environment="NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16"
```

Some ansible playbook I'm already have:

```yaml
- name: Apply tasks for docker servers
  hosts: k8scluster1
  become: yes
  environment: "{{ proxy_env }}"
  tasks:
    - name: install docker ansible dependencies
      pip:
        name: docker-py
        state: present
    - name: create /etc/systemd/system/docker.service.d
      file: 
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: setup proxy env for docker
      template:
        src: docker/docker.service-http-proxy.conf
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
```

Template file in `templates/docker/docker.service-http-proxy.conf`

```yaml
[Service]
Environment="HTTP_PROXY={{ proxy_env.http_proxy }}"
Environment="NO_PROXY={{ proxy_env.no_proxy }}"
```

These are just examples, the vars should be changed to the ones used by kismatic.
If I have some time on the next days, I'm will send pull request.
