### ISSUE TITLE
confusion about multiple roles

### ISSUE THREAD

**Issue by kmkramer** [apprenda/kismatic#1205]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST. also FYI I can't seem to JOIN the slack channel or I'd ask there.

**What happened**: - Two different nodes cannot have the same hostname "master-etcd-0.domain.com"

**What you expected to happen**: find documentation to support requirements and example node declarations for multiple roles.

**How to reproduce it (as minimally and precisely as possible)**: tried labels and taints

**Anything else we need to know?**:

**Environment**: bare-metal 3 master/etcd  with 3 worker nodes
- Kismatic version (use `kismatic version`): 1.10
- Plan file Gist (remove sensitive information if any): 
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from /etc/os-release):  16.04.4 LTS
- Kernel (e.g. `uname -a`): 4.4.0-119-generic

**Comment by dkoshkin** [comment]
@kmkramer 

For nodes to share roles just specify the same details in multiple sections, here in an example:
```
etcd:
  expected_count: 3
  nodes:
  - host: ip-10-0-3-144.ec2.internal
    ip: 52.90.42.91
    internalip: 10.0.3.144
  - host: ip-10-0-3-95.ec2.internal
    ip: 54.175.84.29
    internalip: 10.0.3.95
  - host: ip-10-0-3-187.ec2.internal
    ip: 54.86.202.255
    internalip: 10.0.3.187
master:
  expected_count: 3
  nodes:
  - host: ip-10-0-3-144.ec2.internal
    ip: 52.90.42.91
    internalip: 10.0.3.144
  - host: ip-10-0-3-95.ec2.internal
    ip: 54.175.84.29
    internalip: 10.0.3.95
  - host: ip-10-0-3-187.ec2.internal
    ip: 54.86.202.255
    internalip: 10.0.3.187
  load_balanced_fqdn: 52.90.61.227
  load_balanced_short_name: 52.90.61.227
worker:
  expected_count: 3
  nodes:
  - host: ip-10-0-3-136.ec2.internal
    ip: 52.23.173.119
    internalip: 10.0.3.136
  - host: ip-10-0-3-180.ec2.internal
    ip: 54.210.130.214
    internalip: 10.0.3.180
  - host: ip-10-0-3-59.ec2.internal
    ip: 18.233.160.117
    internalip: 10.0.3.59
ingress:
  expected_count: 2
  nodes:
  - host: ip-10-0-3-59.ec2.internal
    ip: 18.233.160.117
    internalip: 10.0.3.59
  - host: ip-10-0-3-64.ec2.internal
    ip: 18.233.169.10
    internalip: 10.0.3.64
```
