### ISSUE TITLE
Add config option to create anonymous dashboard access

### ISSUE THREAD

**Issue by ST-DDT** [apprenda/kismatic#1264]
**Feature-Request**

Add config option to create anonymous dashboard access (up to the login page).

**What happened**:

I installed a cluster on 3 CentOS VMs using the default settings.
After the installation I tried accessing the Dashboard using the default URL.
`https://<MasterIP>:<API-Port>/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login`
I got a json HTTP 403 - Access denied for the anonymous user.

**What you expected to happen**:

I expected to see the login page.

**Workarounds**

* Install a browser addon that supplies the access token as header by default and use the same token in the login page again.
* Create a ClusterRole and ClusterRoleBinding for anonymous requests manually.

**How to reproduce it (as minimally and precisely as possible)**:

* Install Cluster
* Access Dashboard using a Browser from an external/non-cluster IP.

**Anything else we need to know?**:

Example `ClusterRole-kubernetes-dashboard-anonymous.yml` (copied from old cluster)

````yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-dashboard-anonymous
rules:
- apiGroups:
  - ""
  resourceNames:
  - 'https:kubernetes-dashboard:'
  resources:
  - services/proxy
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- nonResourceURLs:
  - /ui
  - /ui/*
  - /api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/*
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
````

Create clusterrolebinding 
````bash
 kubectl create clusterrolebinding kubernetes-dashboard-anonymous --clusterrole=kubernetes-dashboard-anonymous --user=system:anonymous
````

Adding these two solves this issue.

**Environment**:
- Kismatic version: 1.12.0
- Kubernetes version: v1.10.5
- Plan file Gist: default
- Hardware configuration: 3VMs @ 2vCPU, 4GB RAM, 40GB disk
- OS: Centos 7.3
- Kernel: Linux kubernetes1 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
