### ISSUE TITLE
Automate the labelling of nodes

### ISSUE THREAD

**Issue by swade1987** [apprenda/kismatic#133]
Would be useful if users had the possibility of specifying labels under each node in the YAML file.

Then KET would execute `kubectl label nodes <node-name> <label-key>=<label-value>` for them during the provisioning process.

**Comment by josephjacks** [comment]
@swade1987 we can build on this exciting upstream work  https://github.com/kubernetes-incubator/node-feature-discovery cc @alexbrand @dkoshkin @dasmb

**Comment by swade1987** [comment]
My suggested approach would be as below:

```
nodes:
  - host: master1
    ip: 
    labels: "name=foo,role=bar"
```
You can then perform a string replace for "," with " " additionally you would need to set `--overwrite=true`

**Usage example**

```
kubectl label [--overwrite] (-f FILENAME | TYPE NAME) KEY_1=VAL_1 ... KEY_N=VAL_N [--resource-version=version]
[options]
```

**Comment by willvrny** [comment]
There is also the possibility of using the array syntax:

```
es:
  - host: master1
    ip: 
    labels: ["name=foo", "role=bar"]
```

**Comment by swade1987** [comment]
@alexbrand @dkoshkin - @willvrny and myself will collab on a PR for this change.

**Comment by swade1987** [comment]
Labels would also be useful for multi-zoning when running in AWS

```
failure-domain.beta.kubernetes.io/region=us-central1
failure-domain.beta.kubernetes.io/zone=us-central1-a
```

**Comment by alexbrand** [comment]
Would be nice to get a proposal for this to discuss the plan file interface.

**Comment by dkoshkin** [comment]
@alexbrand do you see any benefits of not using the `kubelet` method and coming up with a different interface?
```
--node-labels mapStringString    Labels to add when registering the node in the cluster. Labels must be key=value pairs separated by ','.
```

**Comment by alexbrand** [comment]
Meaning having a string field in the plan file that would take a comma-separated list of key,value pairs?

**Comment by dkoshkin** [comment]
Yes, something like:
```
worker:
  expected_count: 1
  nodes:
  - host: ""
    ip: ""
    internalip: ""
    labels: "ssd=true,az=a"
```

**Comment by swade1987** [comment]
@dkoshkin that is what i'd go with.

**Comment by alexbrand** [comment]
I think I am leaning towards taking advantage of YAML and using a list of strings instead of a string that we have to split.

We will probably want to validate them to prevent the user setting `kismatic/*` labels that we depend on, so it might be nice to have them in a list already.

**Comment by dkoshkin** [comment]
The only reservation I have is that `package_repository_urls` is already a comma list.
Option a)
```
worker:
  expected_count: 1
  nodes:
  - host: ""
    ip: ""
    internalip: ""
    labels: "ssd=true,az=east-a"
```
Option b:
```
worker:
  expected_count: 1
  nodes:
  - host: ""
    ip: ""
    internalip: ""
    labels: 
    - "ssd=true"
    - "az=east-a"
```
Option c:
```
worker:
  expected_count: 1
  nodes:
  - host: ""
    ip: ""
    internalip: ""
    labels: 
    - key: ssd
      value: true
    - key: az
      value: east-a
```
I'm in favor of `b`

**Comment by alexbrand** [comment]
Yeah, and that field is actually the one I wish was not a comma-separated list, as we are currently unable to add anything related to a specific repository (I forget what the use case was, but I think we had run into an issue where we would have to break each repository into it's own object. Maybe providing a gpg key? I don't remember).

Option D:
```
  nodes:
  - host: ""
    ip: ""
    internalip: ""
    labels: 
      ssd: true
      az: east-a  
```

**Comment by swade1987** [comment]
IMO - Option A is the best choice otherwise the YAML file is going to grow out of control.

**Comment by alexbrand** [comment]
How many labels do you expect to set? I think I prefer type-safety over the potential of a long file. If length is a concern you can do `labels: {"ssd": "true", az: "east-a"}`, although uglier.

The other thing to consider in this issue is whether we want to support role-level labels:
```
worker:
  expected_count: 1
  node_labels:
    foo: bar
  nodes:
  - host: ""
    ip: ""
    internalip: ""
    labels: 
      ssd: true
      az: east-a
```
