### ISSUE TITLE
Add Worker Failing

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#417]
On AWS
KET: `1.3.alpha`

```
➜  out git:(calico-service-upgrade) ✗ ./kismatic install add-worker ip-10-0-0-54 54.236.20.221 10.0.0.54

Running Pre-Flight Checks On New Worker=============================================
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/apprenda/kismatic/pkg/install.(*ansibleExecutor).buildClusterCatalog(0xc420148be0, 0xc420168000, 0x0, 0x0, 0x11)
	/go/src/github.com/apprenda/kismatic/pkg/install/execute.go:561 +0x91b
github.com/apprenda/kismatic/pkg/install.(*ansibleExecutor).RunPreFlightCheck(0xc420148be0, 0xc420168000, 0xc42001e650, 0xc420165458)
	/go/src/github.com/apprenda/kismatic/pkg/install/execute.go:244 +0x81
github.com/apprenda/kismatic/pkg/cli.runPreFlightOnWorker(0x1700fa0, 0xc420148be0, 0xc420075960, 0xa, 0xc4200e9b00, 0x11, 0x1, 0xc4200759a0, 0x7, 0xc4200759d0, ...)
	/go/src/github.com/apprenda/kismatic/pkg/cli/add_worker.go:135 +0x2b3
github.com/apprenda/kismatic/pkg/cli.doAddWorker(0x16f8400, 0xc42008c008, 0x14f0e3d, 0x15, 0xc420079ef0, 0x7fff5fbff746, 0xc, 0x7fff5fbff753, 0xd, 0x7fff5fbff761, ...)
	/go/src/github.com/apprenda/kismatic/pkg/cli/add_worker.go:91 +0x824
github.com/apprenda/kismatic/pkg/cli.NewCmdAddWorker.func1(0xc4200abb00, 0xc4201425d0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/apprenda/kismatic/pkg/cli/add_worker.go:39 +0x13a
github.com/apprenda/kismatic/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200abb00, 0xc420142510, 0x3, 0x3, 0xc4200abb00, 0xc420142510)
	/go/src/github.com/apprenda/kismatic/vendor/github.com/spf13/cobra/command.go:644 +0x3ef
github.com/apprenda/kismatic/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200aad80, 0xc420144000, 0xc4200ab200, 0xc4200aafc0)
	/go/src/github.com/apprenda/kismatic/vendor/github.com/spf13/cobra/command.go:735 +0x339
github.com/apprenda/kismatic/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200aad80, 0x20, 0x152bb10)
	/go/src/github.com/apprenda/kismatic/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/go/src/github.com/apprenda/kismatic/cmd/kismatic/main.go:29 +0x1a2
```

```
cluster:
  name: kubernetes
  admin_password: Vesnototqafudk935      # This password is used to login to the Kubernetes Dashboard and can also be used for administration without a security certificate
  allow_package_installation: true      # When false, installation will not occur if any node is missing the correct deb/rpm packages. When true, the installer will attempt to install missing packages for you.
  networking:
    type: overlay                        # overlay or routed. Routed pods can be addressed from outside the Kubernetes cluster; Overlay pods can only address each other.
    pod_cidr_block: 172.16.0.0/16        # Kubernetes will assign pods IPs in this range. Do not use a range that is already in use on your local network!
    service_cidr_block: 172.17.0.0/16    # Kubernetes will assign services IPs in this range. Do not use a range that is already in use by your local network or pod network!
    policy_enabled: false                # When true, enables network policy enforcement on the Kubernetes Pod network. This is an advanced feature.
    update_hosts_files: true            # When true, the installer will add entries for all nodes to other nodes' hosts files. Use when you don't have access to DNS.
  certificates:
    expiry: 17520h                       # Self-signed certificate expiration period in hours; default is 2 years.
  ssh:
    user: centos
    ssh_key: /Users/dkoshkin/.ssh/kismatic-integration-testing.pem             # Absolute path to the ssh public key we should use to manage nodes.
    ssh_port: 22
docker_registry:                         # Here you will provide the details of your Docker registry or setup an internal one to run in the cluster. This is optional and the cluster will always have access to the Docker Hub.
  setup_internal: true                  # When true, a Docker Registry will be installed on top of your cluster and used to host Docker images needed for its installation.
  address: ""                            # IP or hostname for your Docker registry. An internal registry will NOT be setup when this field is provided. Must be accessible from all the nodes in the cluster.
  port: 443                              # Port for your Docker registry.
  CA: ""                                 # Absolute path to the CA that was used when starting your Docker registry. The docker daemons on all nodes in the cluster will be configured with this CA.
etcd:
  expected_count: 1
  nodes:
  - host: ip-10-0-0-103
    ip: 34.207.245.70
    internalip: 10.0.0.103
master:
  expected_count: 1
  nodes:
  - host: ip-10-0-0-247
    ip: 52.55.178.153
    internalip: 10.0.0.247
  load_balanced_fqdn: 52.55.178.153
  load_balanced_short_name: 10.0.0.247
worker:
  expected_count: 1
  nodes:
  - host: ip-10-0-0-41
    ip: 52.201.235.166
    internalip: 10.0.0.41
  # - host: ip-10-0-0-54
  #   ip: 54.236.20.221
  #   internalip: 10.0.0.54
ingress:
  expected_count: 1
  nodes:
  - host: ip-10-0-0-41
    ip: 52.201.235.166
    internalip: 10.0.0.41
storage:
  expected_count: 0
  nodes:
```
