### ISSUE TITLE
`kismatic info` returns IP addresses, but that information can't be used to run `kismatic ssh` on ip.

### ISSUE THREAD

**Issue by dutronlabs** [apprenda/kismatic#472]
This is more of a usability bug, but see below: 

```
[root@hqs-kuber08 kismatic-1.3.0]# kismatic info
Cluster: v1.3.0

Nodes:
  - 10.5.6.231: v1.3.0 [etcd]
  - 10.5.6.232: v1.3.0 [etcd]
  - 10.5.6.233: v1.3.0 [etcd]
  - 10.5.6.230: v1.3.0 [master][root@hqs-kuber08 kismatic-1.3.0]# kismatic info
Cluster: v1.3.0

Nodes:
  - 10.5.6.231: v1.3.0 [etcd]
  - 10.5.6.232: v1.3.0 [etcd]
  - 10.5.6.233: v1.3.0 [etcd]
  - 10.5.6.230: v1.3.0 [master]
  - 10.5.6.234: v1.3.0 [worker ingress storage]
  - 10.5.6.235: v1.3.0 [worker ingress storage]
  - 10.5.6.236: v1.3.0 [worker storage]

[root@hqs-kuber08 kismatic-1.3.0]# kismatic ssh 10.5.6.230
SSH error "10.5.6.230": node "10.5.6.230" not found in the plan
```

My proposal here would be to add an improvement to search for both the hostname and/or ip, or add the host information here under `kismatic info` to direct a consumer to use the hostname for `kismatic ssh`
