### ISSUE TITLE
kismatic Timed out waiting for at least one DNS pod to be in the ready state

### ISSUE THREAD

**Issue by flyer103** [apprenda/kismatic#476]
I tried to deploy a kubernetes cluster on a Virtualbox node for testing but got the error `kismatic Timed out waiting for at least one DNS pod to be in the ready state`.
Then I tried to deploy a two-node cluster but got the same problem.

The following is basic info:

- OS: MacOS 10.12.4 
- VM OS: ubuntu-16.04
- kismatic version: v1.2.2

The plan file:

```yaml
cluster:
  name: kubernetes
  admin_password: Selnemakyidi36416
  allow_package_installation: true
  disconnected_installation: false
  networking:
    type: overlay
    pod_cidr_block: 172.21.0.0/16
    service_cidr_block: 172.22.0.0/16
    policy_enabled: false
    update_hosts_files: false
  certificates:
    expiry: 17520h
  ssh:
    user: vagrant
    ssh_key: /Users/flyer/.ssh/id_rsa
    ssh_port: 22
docker_registry:
  setup_internal: false
  address: ""
  port: 8443
  CA: ""
etcd:
  expected_count: 1
  nodes:
  - host: "kismatic"
    ip: "172.20.20.23"
    internalip: ""
master:
  expected_count: 1
  load_balanced_fqdn: "kismatic"
  load_balanced_short_name: "kismatic"
  nodes:
  - host: "kismatic"
    ip: "172.20.20.23"
    internalip: ""
worker:
  expected_count: 1
  nodes:
  - host: "kismatic"
    ip: "172.20.20.23"
    internalip: ""
ingress:
  expected_count: 0
  nodes: []
storage:
  expected_count: 0
  nodes: []
nfs:
  nfs_volume: []
```

The screeshot:

<img width="678" alt="image" src="https://cloud.githubusercontent.com/assets/829039/24782840/444fa772-1b7b-11e7-88e2-b00f4fc7cb70.png">
