### ISSUE TITLE
Problems when upgrading Calico CNI Plugin to v1.7.0

### ISSUE THREAD

**Issue by Platzii** [apprenda/kismatic#515]
Hi guys

We wanted to test the new [cni-plugin v1.7.0](https://github.com/projectcalico/cni-plugin/releases/tag/v1.7.0) on our cluster but ran into some problems while deploying it using Kismatic.

On startup of the container the values for `etcd_key_file`, `etcd_cert_file` and `etcd_ca_cert_file` in the CNI config (`/etc/cni/net.d/10-calico.conf`) change to empty values (`""`).

We did some debugging on this and found that this was caused by [this script](https://github.com/projectcalico/cni-plugin/blob/v1.7.0/k8s-install/scripts/install-cni.sh) which overwrites the CNI config file.
The only reason this worked on v1.6.x was because of a [bug, fixed in 1.7.0](https://github.com/projectcalico/cni-plugin/issues/299) in the script which caused that the config file could not be overwritten.

Imo, there are 2 possible ways to fix this problem:

1. Quick and 'dirty' way
As you can see in the script, it uses the env vars `CNI_CONF_ETCD_CA`, `CNI_CONF_ETCD_CERT` and `CNI_CONF_ETCD_KEY`.
If the vars are set to the paths in the calico-config configmap, the problem is solved.
```
        - name: CNI_CONF_ETCD_CA
          valueFrom:
            configMapKeyRef:
              key: etcd_ca
              name: calico-config
        - name: CNI_CONF_ETCD_CERT
          valueFrom:
            configMapKeyRef:
              key: etcd_cert
              name: calico-config
        - name: CNI_CONF_ETCD_KEY
          valueFrom:
            configMapKeyRef:
              key: etcd_key
              name: calico-config
```

2. The 'Calico' way
According to install-cni.sh, there should be a folder `/calico-secrets` (can be overwritten by setting the TLS_ASSETS_DIR var) containing the 3 pem-files, named: etcd-ca, etcd-cert and etcd-key.
The vars will then be set by the script, that's what it is supposed to do at least.

We did choose for option 1 because it was the most simple solution to get it running on our dev environment although I don't think this is the recommended solution to this problem because it's a bit hacky.

Hope you can do something with this information ;)

Kind regards
Simon
