### ISSUE TITLE
Kismatic: function to delete volumes

### ISSUE THREAD

**Issue by xetys** [apprenda/kismatic#542]
there are an add and a list option, but no delete option for volumes

I suggest implementing a `kismatic volume delete` command, which has to

* delete pv with given name
* run `gluster volume stop NAME --mode=script && gluster volume delete NAME --mode=script` to delete the gluster volume

**Comment by dkoshkin** [comment]
Currently KET creates the directory for the volume, when the volume is deleted should KET also delete the directory? 
If the directory is not deleted a volume with the same name would contain the contents of the old volume.

**Comment by xetys** [comment]
Ok, I will find out. As I started learning golang and already did a
contribution in it to another project, I could PR this if there is interest
in this

**Comment by TimWoolford** [comment]
Deleting the gluster volume does not necessarily remove the underlying files, and attempts to reuse these directories will fail due to clashes with the `.glusterfs` metadata. You will need to clear out the bricks manually.

We're using an ansible task that goes something like: (_n.b. out of context so wont run as is - edited to protect the innocent_)
```
- name: collect current volumes
  become: true
  delegate_to: "{{ groups['storage'][0] }}"
  run_once: true
  shell: gluster volume list
  register: current_volumes
  changed_when: false

- block:
    - name: gather brick information for volume '{{ gluster_volume_name }}'
      become: true
      delegate_to: "{{ groups['storage'][0] }}"
      run_once: true
      shell: gluster volume info {{ gluster_volume_name }} | grep -e "^Brick[0-9]" | cut -d " " -f 2
      register: bricks
      changed_when: false

    - name: remove gluster volume '{{ gluster_volume_name }}'
      become: true
      delegate_to: "{{ groups['storage'][0] }}"
      gluster_volume:
        name: "{{ gluster_volume_name }}"
        state: absent
      run_once: true

    - name: delete brick directory
      become: true
      run_once: true
      delegate_to: "{{ item.split(':')[0] }}"
      file:
         name: "{{ item.split(':')[1] }}"
         state: absent
      with_items: "{{ bricks.stdout_lines }}"

  when: "gluster_volume_name in current_volumes.stdout_lines"

```
