### ISSUE TITLE
Cluster Monitoring

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#551]
Add monitoring to the cluster.  
Using prometheus and grafana Helm charts.

Plan file changes:
```
cluster:
...
features:
  package_manager:
    enabled: true
    provider: helm
  heapster:
    enabled: true
    storage:
      persistent_volume_claim: ""
  monitoring:
    enabled: true
    prometheus:
      values: "" # path to the file to override any helm variable
      storage:
        alertmanager_persistent_volume_claim: ""
        server_persistent_volume_claim: ""
    grafana:
      values: ""
      storage:
        server_persistent_volume_claim: ""
```

Inspector changes:
**node exporter port**: 9100

Package Changes:
```
    Image: appropriate/curl:latest
    Image: quay.io/coreos/grafana-watcher:v0.0.4
    Image: grafana/grafana:latest
    Image: prom/alertmanager:v0.5.1
    Image: jimmidyson/configmap-reload:v0.1
    Image: prom/node-exporter:v0.13.0
    Image: gcr.io/google_containers/kube-state-metrics:v0.4.1
    Image: prom/prometheus:v1.5.2
```

Things to consider
- should `values:` be a `map[string]string` or the path to a file, both?
  - this will impact the ability to add/modify graphs to deploy:
  - leaning towards to both, helm already [handles all the merging](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/values_files.md)
- ~if a user wants to upgrade a chart how do they get the variables we used to set it up~ - there is a flag on `helm upgrade --reuse-values` that will preserve the previous release values, they will be joined with any new values passed in
- how to monitor etcd?
