### ISSUE TITLE
After upgrade to 1.7 from 1.6.4 K8s is still in 1.6.4

### ISSUE THREAD

**Issue by spmoreno** [apprenda/kismatic#628]
Hi, I ran an offline upgrade using Kismatic 1.4 (using the same manifest from the installation), everything ran ok but after the cluster is still in K8s 1.6.4. Docker images at every nodes are still the same.

Do I have to something else?
e.g: reboot machines, etc.

Cheers.

**Comment by dkoshkin** [comment]
Hello @spmoreno:
What is the output when you run `./kismatic info`?
What OS are you using?
Where are the nodes running, cloud, baremetal, etc?
What version of installer are you using `darwin` or `linux`?

**Comment by spmoreno** [comment]
Hi @dkoshkin 

> What is the output when you run ./kismatic info?
Nodes:
Name       IP              Roles    Kismatic Version
etcd1      xx.xx.xx.xx    etcd     1.4.0
etcd2      xx.xx.xx.xx    etcd     1.4.0
etcd3      xx.xx.xx.xx    etcd     1.4.0
master1    xx.xx.xx.xx    master   1.4.0
master2    xx.xx.xx.xx    master   1.4.0
worker1    xx.xx.xx.xx    worker   1.4.0
worker2    xx.xx.xx.xx    worker   1.4.0
worker3    xx.xx.xx.xx    worker   1.4.0
ingress1   xx.xx.xx.xx    worker   1.4.0
ingress2   xx.xx.xx.xx   worker   1.4.0

> What OS are you using?
All nodes are the same: Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> Where are the nodes running, cloud, baremetal, etc?
Cloud (Linode)

> What version of installer are you using darwin or linux?
Linux

**Comment by dkoshkin** [comment]
Can you share the output of:
`kubectl cluster-info`
`kubectl get nodes`
`kubectl describe pods -n kube-system | grep Image:`

**Comment by spmoreno** [comment]
Yes, of course:

`root@kismatic:~# kubectl cluster-info
Kubernetes master is running at https://xx.xx.newark.lemupress.com:6443
KubeDNS is running at https://xx.xx.newark.lemupress.com:6443/api/v1/namespaces/kube-system/services/kube-dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
root@kismatic:~# kubectl get nodes
NAME       STATUS                     AGE       VERSION
ingress1   Ready                      18d       v1.6.4
ingress2   Ready                      18d       v1.6.4
master1    Ready,SchedulingDisabled   28d       v1.6.4
master2    Ready,SchedulingDisabled   28d       v1.6.4
worker1    Ready                      28d       v1.6.4
worker2    Ready                      28d       v1.6.4
worker3    Ready                      28d       v1.6.4
root@kismatic:~# kubectl describe pods -n kube-system | grep Image:
    Image:              calico/node:v1.2.1
    Image:              calico/cni:v1.8.3
    Image:              calico/node:v1.2.1
    Image:              calico/cni:v1.8.3
    Image:              calico/node:v1.2.1
    Image:              calico/cni:v1.8.3
    Image:              calico/node:v1.2.1
    Image:              calico/cni:v1.8.3
    Image:              calico/node:v1.2.1
    Image:              calico/cni:v1.8.3
    Image:              calico/node:v1.2.1
    Image:              calico/cni:v1.8.3
    Image:              calico/node:v1.2.1
    Image:              calico/cni:v1.8.3
    Image:              calico/kube-policy-controller:v0.6.0
    Image:              gcr.io/google-containers/kube-apiserver-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-apiserver-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-controller-manager-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-controller-manager-amd64:v1.6.4
    Image:              gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1
    Image:              gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1
    Image:              gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1
    Image:              gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1
    Image:              gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1
    Image:              gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1
    Image:              gcr.io/google-containers/kube-proxy-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-proxy-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-proxy-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-proxy-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-proxy-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-proxy-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-proxy-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-scheduler-amd64:v1.6.4
    Image:              gcr.io/google-containers/kube-scheduler-amd64:v1.6.4
    Image:              gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
    Image:              gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
    Image:              docker.io/spotify/docker-gc:latest
    Image:              docker.io/spotify/docker-gc:latest
    Image:              docker.io/spotify/docker-gc:latest
    Image:              docker.io/spotify/docker-gc:latest
    Image:              docker.io/spotify/docker-gc:latest
    Image:              docker.io/spotify/docker-gc:latest
    Image:              docker.io/spotify/docker-gc:latest
    Image:              gcr.io/kubernetes-helm/tiller:v2.4.2
    Image:              gcr.io/kubernetes-helm/tiller:v2.4.2`

**Comment by dkoshkin** [comment]
None of the images have been updated, it's like the upgrade didn't even run although the final step of upgrading a KET version file was performed.
Are you able to SSH into the master and check `/etc/kubernetes/specs` and `/etc/kubernetes/manifests` to see if those files have modified with the new versions, DNS should be `1.14.4`, dashboard `1.6.1`.

**Comment by spmoreno** [comment]
I checked them and they're in kismatic/version: "1.4.0" but old manifests:

```
root@master1:/etc/kubernetes/specs# cat kubernetes-dashboard.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
    version: "v1.6.0"
    kismatic/version: "1.4.0"
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 2  # create 2 replicas or the number of worker nodes
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: kubernetes-dashboard
        image: "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"
        imagePullPolicy: IfNotPresent
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9090
          protocol: TCP
        args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 9090
  selector:
    k8s-app: kubernetes-dashboard
```

```
root@master1:/etc/kubernetes/specs# cat kubernetes-dns.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists

---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 172.20.0.2
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
  annotations:
    kismatic/version: "1.4.0"
spec:
  replicas: 2  # create 2 replicas or the number of worker nodes
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      volumes:
      # Configures DNS to communicate with the master.
      # Relies on a kubeconfig file on the worker.
      - name: "worker-kubeconfig"
        hostPath:
          path: "/var/lib/kubelet/kubeconfig"
      - name: "ssl-certs"
        hostPath:
          path: "/etc/kubernetes/ca.pem"
      - name: kube-dns-config
        configMap:
          name: kube-dns
          optional: true
      containers:
      - name: kubedns
        image: "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1"
        resources:
          # TODO: Set memory limits when we've profiled the container for large
          # clusters, then set request = limit to keep this container in
          # guaranteed class. Currently, this container falls into the
          # "burstable" category so the kubelet doesn't backoff from restarting it.
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        livenessProbe:
          httpGet:
            path: /healthcheck/kubedns
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          # we poll on pod startup for the Kubernetes master service and
          # only setup the /readiness HTTP server once that's available.
          initialDelaySeconds: 3
          timeoutSeconds: 5
        args:
        - --domain=cluster.local
        - --dns-port=10053
        - --config-dir=/kube-dns-config
        - --kubecfg-file=/root/.kube/config
        - --v=2
        # env:
        # - name: PROMETHEUS_PORT
        #   value: "10055"
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
        # - containerPort: 10055
        #   name: metrics
        #   protocol: TCP
        volumeMounts:
        - mountPath: /etc/kubernetes/ca.pem
          name: "ssl-certs"
        - mountPath: /root/.kube/config
          name: "worker-kubeconfig"
        - name: kube-dns-config
          mountPath: /kube-dns-config
      - name: dnsmasq
        image: "gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1"
        livenessProbe:
          httpGet:
            path: /healthcheck/dnsmasq
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - -v=2
        - -logtostderr
        - -configDir=/etc/k8s/dns/dnsmasq-nanny
        - -restartDnsmasq=true
        - --
        - -k
        - --cache-size=1000
        - --log-facility=-
        - --server=/cluster.local/127.0.0.1#10053
        - --server=/in-addr.arpa/127.0.0.1#10053
        - --server=/ip6.arpa/127.0.0.1#10053
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        # see: https://github.com/kubernetes/kubernetes/issues/29055 for details
        resources:
          requests:
            cpu: 150m
            memory: 20Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/ca.pem
          name: "ssl-certs"
        - mountPath: /root/.kube/config
          name: "worker-kubeconfig"
        - name: kube-dns-config
          mountPath: /kube-dns-config
      - name: sidecar
        image: "gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - --v=2
        - --logtostderr
        - --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
        - --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
        ports:
        - containerPort: 10054
          name: metrics
          protocol: TCP
        resources:
          requests:
            memory: 20Mi
            cpu: 10m
      dnsPolicy: Default  # Don't use cluster DNS.
```
