### ISSUE TITLE
Version labels for all cluster components

### ISSUE THREAD

**Issue by jonnymatts** [apprenda/kismatic#629]
Version labels on cluster components would be useful for cluster monitoring.

For example, the kubedns and calico pods.

**Comment by willvrny** [comment]
Hey @jonnymatts, 

It would good to expand this a little bit more. 

- What components do you want specifically? 
- Are you just expecting a `version: 1.0.0` label?

It looks like this could be done with a change to the yaml files in the Ansible part of Kismatic.

@dkoshkin & @alexbrand can we label this as 'help wanted'. This would be a good starting point for anyone looking to contribute.

**Comment by swade1987** [comment]
Would also be useful to have the kubernetes version as a label on all component pods.

**Comment by jonnymatts** [comment]
It would be good to get this information for all of the components that Kismatic installs for you. A label like you have suggested would be great.

**Comment by swade1987** [comment]
@jonnymatts sounds good I will work with the team to get working on this.

**Comment by alexbrand** [comment]
I am curious about the use case here, as the version is readily available in the podspec.

**Comment by jonnymatts** [comment]
We add the versions of our other components as a label so it will be scraped by prometheus. We use these values to show the versions of our dependencies in a dashboard.

**Comment by willvrny** [comment]
With the right logging tools we can also get the label as metadata on the logs for debugging purposes.

**Comment by dkoshkin** [comment]
@jonnymatts and @willvrny how do you see a deployment with multiple containers working? 
Also for your usecase does it have to be a label or can it be an annotation?

**Comment by jonnymatts** [comment]
I think it would have to be a label for Prometheus to scrape it. And I would imagine a label like '<component>_version: 1.0.0' so it should work with multiple containers. What do you think?

**Comment by willvrny** [comment]
@jonnymatts So as an example for kube-dns on the deployment we'd have:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubedns_version: "1.14.5"
    kubedns_dnsmasq_version: "1.14.5"
    kubedns_sidecar_version: "1.14.5"
  annotations:
    kismatic/version: "{{ kismatic_short_version }}"
spec:
...
```

And that would handle the multiple containers especially if they have separate versions. Only downside is that the label won't be common across all resources. I'd also suggest that even if a resource only had a single container it would still follow the '<container_name>_version' key format.

If necessary a wildcard pattern could be used to grab these labels across multiple resources e.g. `*_version`?
