### ISSUE TITLE
Commented plan file is hard to read

### ISSUE THREAD

**Issue by alexbrand** [apprenda/kismatic#696]
The current commenting strategy that has comments in line with the actual fields has grown a bit unreadable. Some of the lines wrap around and make it even harder to understand what is going on.

I think we should template out a plan file in the following manner:
* Add comments above each field that requires a comment. Break the line into multiple lines if it is longer than 80 characters.
* Options should go on the next line, after explaining the field.

For example:
```
add_ons:
  cni:
    disable: false
    # The provider that should be used for the CNI add-on. The 'custom' 
    # option will result in a CNI ready cluster, however it is up to you to 
    # configure a CNI plugin after the installation.
    # Options: 'calico','weave','contiv','custom'. 
    provider: calico                                        
    options:
      calico:
        # The calico data path mode. Routed pods can be addressed from outside
        # the Kubernetes cluster; Overlay pods can only address each other.
        # Options: 'overlay','routed'. 
        mode: overlay                                                    
```
