### ISSUE TITLE
Upgrade Nginx Ingress Controller

### ISSUE THREAD

**Issue by jonmosco** [apprenda/kismatic#854]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**FEATURE REQUEST**

**What happened**:

Current version of Kismatic (1.6.0) still uses an oldder version Nginx Ingress controller: 0.8.3 

From group_vars/container_images.yaml:

```yaml
  nginx_ingress_controller:
    name: gcr.io/google_containers/nginx-ingress-controller
    version: 0.8.3
```

**What you expected to happen**:

Can this version be updated to current or at least in the 0.9.x to take advantage of all the new features?

**Environment**:
- Kismatic version (use `kismatic version`): 1.6.0
